# import unittest
# import exceptiontest1

while True:
    try:
        age = int(input("Age is :"))
        print (f'Age is {age}')
        break
    except ValueError:
        print ("Input is invalid.")

# This is a test comment
